version: '2'
services:
    auth-app:
        image: auth
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://auth-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=auth
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    auth-mongodb:
        extends:
            file: mongodb.yml
            service: auth-mongodb
